# -*- coding: utf-8 -*-
"""Copy of Student_performance_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148AtZhep7L2k1OrnFfPpOmkqImX-yxgx
"""

# import necessary libraries
import pandas as pd
import numpy as np

# loading the dataset from excel file to pandas DataFrame
df=pd.read_csv("/student-por.csv")

# first 5 rows of the dataframe
df.head()

# number of data points & number of features
df.shape

print('Describing the Dataset:')
print(df.describe())

df.info()

# checking for missing values
df.isna().sum()

#need name of categorical columns
categorical_cols = df.select_dtypes(include='object').columns
print(categorical_cols)

#shows unique feature of our column
for i in categorical_cols:
  print(df[i].unique())

from sklearn.preprocessing import LabelEncoder
for i in [0,1,3,4,5,8,9,10,11,15,16,17,18,19,20,21,22]:
  df[i]=LabelEncoder().fit_transform(df[i])
print(df.head())